ddy:
   swagger:
      basePackage: com.ddy.EatFood
      version: 0.2

Server:
  port: 8070

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eatfood?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: ddy5529
    driverClassName: com.mysql.jdbc.Driver
  freemarker:
    prefer-file-system-access: false
  jpa:
    properties:
      format_sql: true
      show-sql: true
      hibernate:
            ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect


mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml


ddy:
  name: ddy
#logging:
#  file: logs/system.log
#  level:
#    root: INFO
#    org.springframework.web: DEBUG
#    org.mybatis: DEBUG
#    org.apache.ibatis: DEBUG

