ddy:
   swagger:
      basePackage: com.ddy.EatFood
      version: 0.2

spring:
  datasource:
    url: jdbc:mysql://10.83.20.160:3306/ctm?useUnicode=true&characterEncoding=utf-8
    username: root
    password: bqjr@2018
    driverClassName: com.mysql.jdbc.Driver
  freemarker:
    prefer-file-system-access: false

mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml

logging:
  file: logs/system.log
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG

